
project:
  type: website
  output-dir: ../docs

website:
  title: "æˆ‘çš„IAéƒ¨è½æ ¼"
  site-url: "https://bigflowerfrancis.github.io/MyWebsite"
  repo-url: "https://github.com/bigflowerfrancis/MyWebsite"
  navbar:
    left:
      - text: é¦–é 
        href: index.html
      - text: AIæ™‚ä»£çš„æ•™è‚²
        href: column.html
      - text: AI Coachå°ˆå€
        href: journey.html
    right:
      - icon: github
        href: https://github.com/bigflowerfrancis/MyWebsite
  sidebar:
    style: floating
    search: true
    contents:
      - index.qmd
      - column.qmd
      - section: "âœï¸å°ˆæ¬„æ–‡ç« "
        contents:
          - text: To Prompt or Not to Promptï¼šç”¨æç¤ºèªé–‹å•Ÿäººæ©Ÿå”ä½œçš„æ™ºæ…§ä¹‹æ—…
            href: /column/2025-04-12-Article.html
          - text: å¾æ¨ç†AIåæ€AIæ™‚ä»£çš„æ•™è‚²è½‰å‹ï¼šé‡æ–°è¨­è¨ˆå­¸ç¿’çš„èµ·é»
            href: /column/2025-04-18-Article.html
      - journey.qmd
      - section: "ğŸ“˜å­¸ç¿’å‚™å¿˜"
        contents:
          - text: å¾æŠ€è¡“å…¥é–€åˆ°é¢¨æ ¼æˆå½¢çš„çŸ¥è­˜æ—…ç¨‹
            href: /journey/2025-04-13-AICoach.html
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    code-fold: true
    code-summary: "é¡¯ç¤ºç¨‹å¼ç¢¼"
    number-sections: false
  
