
project:
  type: website
  output-dir: ../docs

website:
  title: "æˆ‘çš„IAéƒ¨è½æ ¼"
  site-url: "https://bigflowerfrancis.github.io/MyWebsite"
  repo-url: "https://github.com/bigflowerfrancis/MyWebsite"
  navbar:
    left:
      - text: é¦–é 
        href: index.html
      - text: å°ˆæ¬„ç«‹å ´
        href: post.html
      - text: AIæ™‚ä»£çš„æ•™è‚²
        href: article.html
      - text: AI Coachå°ˆå€
        href: aicoach.html
    right:
      - icon: github
        href: https://github.com/bigflowerfrancis/MyWebsite
  sidebar:
    style: floating
    search: true
    contents:
      - index.qmd
      - post.qmd
      - article.qmd
      - section: "âœï¸å°ˆæ¬„æ–‡ç« "
        contents:
          - text: å¾æ¨ç†AIåæ€AIæ™‚ä»£çš„æ•™è‚²è½‰å‹ï¼šé‡æ–°è¨­è¨ˆå­¸ç¿’çš„èµ·é»
            href: /article/2025-04-18-Article.html
      - aicoach.qmd
      - section: "ğŸ“˜å­¸ç¿’å‚™å¿˜"
        contents:
          - text: å¾æŠ€è¡“å…¥é–€åˆ°é¢¨æ ¼æˆå½¢çš„çŸ¥è­˜æ—…ç¨‹
            href: /aicoach/2025-04-13-AICoach.html
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    code-fold: true
    code-summary: "é¡¯ç¤ºç¨‹å¼ç¢¼"
    number-sections: false
  
